name: Spring Boot CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SUBMODULE_PRIVATE_KEY }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Check secrets file
        run: ls -R src/main/resources/secrets

      - name: Debug Profile
        run: cat src/main/resources/secrets/application-prod.yml

      - name: Build without test
        run: ./gradlew clean build -x test -Dspring.profiles.active=prod

      - name: Run Tests
        run: ./gradlew test -Dspring.profiles.active=prod

      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Copy to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu"

      - name: Restart App
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f 'java -jar' || true
            rm -f app.log
            nohup java -jar /home/ubuntu/*.jar > app.log 2>&1 &
